import Foundation

/// Immutable catalogs can also be constructed with explicit preferences in
/// isolated checks. Production uses macOS's per-app preferred language list.
public struct TranslationCatalog {
    public let language: String
    private let selected: Bundle
    private let fallback: Bundle

    public init(bundle: Bundle = L10n.resources, preferences: [String] = Locale.preferredLanguages) {
        language = Bundle.preferredLocalizations(from: ["en", "zh-Hans"], forPreferences: preferences).first ?? "en"
        fallback = Bundle(path: bundle.path(forResource: "en", ofType: "lproj") ?? "") ?? bundle
        selected = Bundle(path: bundle.path(forResource: language, ofType: "lproj") ?? "") ?? fallback
    }

    public func text(_ key: String, _ arguments: CVarArg...) -> String { format(key, arguments: arguments) }

    /// Only known plain-string diagnostic keys and their exact string argument
    /// count can be formatted from a peer. Unknown/legacy input stays literal.
    public func remoteError(key: String?, arguments: [String]?, fallback: String) -> String {
        guard let key, let expected = RemoteErrorFields[key], let arguments,
              arguments.count == expected, arguments.allSatisfy({ $0.utf8.count <= 4096 }) else { return fallback }
        return format(key, arguments: arguments.map { $0 as CVarArg })
    }

    func format(_ key: String, arguments: [CVarArg]) -> String {
        let missing = "__PeerJetty_missing_translation__"
        var template = selected.localizedString(forKey: key, value: missing, table: "Localizable")
        if template == missing { template = fallback.localizedString(forKey: key, value: key, table: "Localizable") }
        guard !arguments.isEmpty else { return template }
        return String(format: template, locale: Locale(identifier: language), arguments: arguments)
    }
}

/// This local UI preference never enters pairing or transfer configuration.
public enum DisplayLanguage: String, CaseIterable {
    case system, english = "en", simplifiedChinese = "zh-Hans"
    public func preferences(systemLanguages: [String]) -> [String] {
        self == .system ? systemLanguages : [rawValue]
    }
}

public struct LanguagePreferences {
    private let defaults: UserDefaults
    private static let key = "PeerJettyDisplayLanguage"
    public init(defaults: UserDefaults = .standard) { self.defaults = defaults }
    public var selection: DisplayLanguage {
        DisplayLanguage(rawValue: defaults.string(forKey: Self.key) ?? "") ?? .system
    }
    public func save(_ selection: DisplayLanguage) {
        if selection == .system { defaults.removeObject(forKey: Self.key) }
        else { defaults.set(selection.rawValue, forKey: Self.key) }
    }
}

public enum L10n {
    public static var resources: Bundle {
        // Assembled apps carry .lproj folders in their own Resources directory.
        // They must never depend on the developer's SwiftPM build directory.
        if Bundle.main.path(forResource: "en", ofType: "lproj") != nil { return .main }
        #if SWIFT_PACKAGE
        return .module
        #else
        return .main
        #endif
    }
    private static let catalog = TranslationCatalog(preferences: LanguagePreferences().selection.preferences(systemLanguages: Locale.preferredLanguages))
    public static var language: String { catalog.language }
    public static func text(_ key: String, _ arguments: CVarArg...) -> String { catalog.format(key, arguments: arguments) }
    public static func message(_ key: String, arguments: [String]) -> String {
        catalog.format(key, arguments: arguments.map { $0 as CVarArg })
    }
    public static func remoteError(key: String?, arguments: [String]?, fallback: String) -> String {
        catalog.remoteError(key: key, arguments: arguments, fallback: fallback)
    }
    public static func percent(_ value: Int) -> String {
        let formatter = NumberFormatter(); formatter.locale = .current
        formatter.numberStyle = .percent; formatter.maximumFractionDigits = 0
        return formatter.string(from: NSNumber(value: Double(min(100, max(0, value))) / 100)) ?? "\(value)%"
    }
}

// This allowlist covers only diagnostic keys generated by PeerError.localized.
// Keep its field counts aligned with the catalog and verify them in checks.
private let RemoteErrorFields: [String: Int] = [
    "filestore.could_not_commit_received_files_saved_count": 2,
    "filestore.could_not_create_the_received_file": 1,
    "filestore.could_not_read_file": 1,
    "filestore.directory_depth_or_file_count_exceeds_the_limit": 0,
    "filestore.file_data_length_does_not_match": 0,
    "filestore.file_integrity_check_failed": 0,
    "filestore.invalid_file_order": 0,
    "filestore.the_file_was_not_received_completely": 0,
    "filestore.the_receive_folder_does_not_exist_choose_it": 0,
    "filestore.the_receive_folder_is_not_writable": 0,
    "filestore.the_receiving_device_has_insufficient_disk_space": 0,
    "filestore.the_source_file_no_longer_exists": 0,
    "filestore.the_transfer_is_not_complete": 0,
    "filestore.unsupported_file_type": 1,
    "framing.connection_closed_or_message_too_large": 0,
    "framing.invalid_message_length": 0,
    "framing.invalid_message_type": 0,
    "framing.the_other_device_disconnected": 0,
    "identity.could_not_generate_secure_random_data": 0,
    "identity.could_not_load_the_local_identity": 1,
    "identity.could_not_read_the_keychain_identity": 1,
    "identity.could_not_reset_the_local_identity": 1,
    "identity.could_not_save_the_keychain_identity": 1,
    "identity.could_not_verify_the_pairing_code": 0,
    "identity.local_identity_generation_failed": 1,
    "identity.the_local_certificate_is_invalid": 0,
    "identity.the_other_device_did_not_provide_an_identity": 0,
    "identity.tls_connection_information_is_missing": 0,
    "identity.tls_identity_is_missing": 0,
    "models.a_symbolic_link_chain_points_outside_the_receive": 0,
    "models.a_symbolic_link_points_outside_the_receive_folder": 0,
    "models.file_size_exceeds_the_limit": 0,
    "models.invalid_file_manifest": 0,
    "models.invalid_file_path": 0,
    "models.invalid_filename": 0,
    "models.invalid_link_information": 0,
    "models.invalid_parent_directory": 0,
    "models.only_relative_symbolic_links_within_the_same_root": 0,
    "models.select_the_actual_file_instead_of_a_top": 0,
    "models.symbolic_link_target_is_missing": 0,
    "models.symbolic_links_form_a_cycle_or_an_excessively": 0,
    "models.the_file_manifest_contains_duplicate_paths": 0,
    "models.the_file_manifest_has_no_root_entry": 0,
    "models.too_many_files": 0,
    "pairing.pairing_proof_does_not_match_connection_rejected": 0,
    "peerengine.connection_closed": 0,
    "peerengine.device_identity_or_protocol_does_not_match": 0,
    "peerengine.device_trust_removed": 0,
    "peerengine.duplicate_or_premature_pairing_confirmation": 0,
    "peerengine.invalid_acceptance_message": 0,
    "peerengine.invalid_file_data": 0,
    "peerengine.invalid_file_end_message": 0,
    "peerengine.invalid_file_start_message": 0,
    "peerengine.invalid_pairing_step": 0,
    "peerengine.invalid_rejection_message": 0,
    "peerengine.invalid_save_receipt": 0,
    "peerengine.invalid_transfer_end_message": 0,
    "peerengine.pairing_cancelled": 0,
    "peerengine.pairing_is_closed": 0,
    "peerengine.pairing_timed_out": 0,
    "peerengine.pairing_was_not_confirmed": 0,
    "peerengine.receiver_busy_or_invalid_manifest": 0,
    "peerengine.service_stopped": 0,
    "peerengine.the_file_changed_during_sending_try_again": 0,
    "peerengine.the_source_file_became_shorter_or_unreadable": 0,
    "peerengine.too_many_pairing_requests_or_another_pairing_is": 0,
    "peerengine.transfer_cancelled_drop_the_files_again_to_retry": 0,
    "peerengine.transfer_identifier_is_missing": 0,
    "peerengine.transfer_timed_out_check_the_network_and_retry": 0,
    "peerengine.unknown_protocol_message": 0,
    "peerengine.unpaired_devices_cannot_send_files": 0,
    "promisetracker.reading_dropped_files_timed_out_or_was_cancelled": 0,
    "promisetracker.the_source_app_did_not_provide_a_file": 0,
]
